codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  ignore:
    - "benches/**/*"
    - "examples/**/*"
    - "tests/**/*"

  status:
    project:
      default:
        target: 90%
        threshold: 5%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 5%
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true